import cn from "classnames";
import Head from "next/head";

import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { PrimaryButton } from "../components/PrimaryButton";
import { useCollectionStats } from "../hooks/useCollectionStats";
import { nsContractAddress } from "../lib/config";
import { fontStyle } from "../lib/style";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: collectionStats } = useCollectionStats(
    `tori-${nsContractAddress}`
  );
  return (
    <>
      <Head>
        <title>Berty</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <Header />

        <section className={styles.content}>
          <div className={styles.contentContainer}>
            <div className={styles.left}>
              <img src="../img/illustration.svg" alt="Illustration of an egg" />
            </div>
            <div className={styles.right}>
              <h1>
                Berty, the future-proof{" "}
                <span className={styles.txtOrange}>web3</span> messenger is
                coming soon....
              </h1>
            </div>
          </div>
          <div className={styles.bottomContainer}>
            <div className={styles.card}>
              <div className={styles.gradient} />
              <div className={styles.cardContent}>
                <div className={styles.textContainer}>
                  <h2 className={styles.cardTitle}>
                    Subscribe to the Newsletter
                  </h2>
                  <p style={fontStyle()}>
                    Stay up to date with the news from our team and be the first
                    to find out when Berty Messenger will be ready!
                  </p>
                </div>
                <div className={styles.search}>
                  <form
                    action="https://tech.us20.list-manage.com/subscribe/post?u=5ca3993c7f0b8f646dcda714b&amp;id=4d7828715b&amp;f_id=002d95e5f0"
                    method="post"
                    id="mc-embedded-subscribe-form"
                    name="mc-embedded-subscribe-form"
                  >
                    <input
                      className={styles.cardInput}
                      type="text"
                      name="EMAIL"
                      placeholder="Enter your email here"
                      id="mce-EMAIL"
                      required
                    />
                    <PrimaryButton
                      type="submit"
                      value="Subscribe"
                      name="subscribe"
                      id="mc-embedded-subscribe"
                    >
                      Sign-up
                    </PrimaryButton>
                  </form>
                </div>
              </div>
              <div className={styles.line} />
            </div>
            <div className={styles.card}>
              <div className={styles.gradient} />
              <div className={styles.advanced}>
                <p>Advanced</p>
              </div>
              <div className={styles.cardContent}>
                <div className={styles.textContainer}>
                  <h2 className={styles.cardTitle}>
                    Reserve your decentralized identifier
                  </h2>
                  <p style={fontStyle()}>
                    (i) This public username is an ENTIRELY OPTIONAL feature
                    that will allow people to find you via onchain-handle.
                    <br />
                    <span style={{ fontSize: 12 }}>
                      <span style={{ color: "#F3A15E" }}>
                        {collectionStats?.owners || 0}
                      </span>{" "}
                      bertians have already booked their handle
                    </span>
                  </p>
                </div>
                <div className={styles.search}>
                  <form action="/registration" method="get">
                    <input
                      className={styles.cardInput}
                      type="text"
                      placeholder="Verify availablity..."
                      autoCapitalize="off"
                      name="name"
                    />
                    <PrimaryButton>Search</PrimaryButton>
                  </form>
                </div>
              </div>
              <div className={cn(styles.line, styles.lineRight)} />
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
