import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header/header'
import Footer from '../components/footer/footer'
import KeplrButton from './api/keplr'

export default function Home() {

  return (
    <>
      <Head>
        <title>Berty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Body}>

        <Header />

      <section className={styles.content}>
        <div className={styles.contentContainer}>
          <div className={styles.left}>
          <img src="../img/illustration.svg" alt="Illustration of an egg"/>
          </div>
          <div className={styles.right}>
        <div className={styles.text1}>
          <h1>Berty, the future-proof <span className={styles.txtOrange}>web3</span> messenger is coming soon....</h1>
        </div>

        </div>
        </div>
        <div className={styles.bottomContainer}>
      <div className={styles.card}>
        <div className={styles.gradient}>
        </div>
        <div className={styles.textContainer}>
          <h2>Subscribe to the Newsletter</h2>
          <p>Stay up to date with the news from our team and be the first to find out when Berty Messenger will be
            ready!</p>
        </div>
        <div className={styles.search}>
          <form
            action="https://tech.us20.list-manage.com/subscribe/post?u=5ca3993c7f0b8f646dcda714b&amp;id=4d7828715b&amp;f_id=002d95e5f0"
            method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form">
            <input type="text" name="EMAIL" placeholder="Enter your email here" id="mce-EMAIL" required />
            <button className={styles.button} type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe">Sign-up</button>
          </form>
        </div>
        <div className={styles.line}>
        </div>
      </div>
      <div className={styles.card}>
        <div className={styles.gradient}>
        </div>
        <div className={styles.advanced}>
          <p>Advanced</p>
        </div>
        <div className={styles.textContainer}>
          <h2>Reserve your decentralized identifier</h2>
          <p>(i) This public username is an ENTIRELY OPTIONAL feature that will allow people to find you via
            onchain-handle.<br/><span>4503</span> bertians have already booked thier handle</p>
        </div>
        <div className={styles.search}>
          <form action="/registration" method="get">
            <input type="text" placeholder="Verify availablity..." />
            <button className={styles.button} >Connect Wallet</button>
          </form>
              </div>
            <div className={styles.line}>
           </div>
         </div>
        </div>
      </section>

    <Footer />

      </div>
    </>
  )
}
