import Head from 'next/head'
import styles from '../styles/Registration2.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Body}>
        <section className={styles.header}>
          <Link href="/">
            <img className={styles.logo} alt="Berty's company logo" src="../img/logo.svg" />
          </Link>
      <div>
        <ul className={styles.navbar}>
          <li><Link className={styles.hov} href="/vision">Vision</Link></li>
          <li><Link className={styles.hov} href="/roadmap">Roadmap</Link></li>
          <li><Link className={styles.hov} href="/">Contribute</Link></li>
          <a href="#" className={styles.close}><i className={`${styles.fa} ${styles.faTimes}`}></i></a>
        </ul>
    </div>
    <div  className={`${styles.barContainer} ${styles.mobile}`}>
      <i className={`${styles.faSolid} ${styles.faBars} ${styles.bar}`}></i>
    </div>
    </section>

    <section className={styles.registration3}>
        <div className={styles.leftWrapper}>
            <div className={styles.stepsArray}>
                <div className={styles.back}>
                    <a href="registration.html"><img src="../img/arrow.png" alt="Back arrow icon"/>
                    </a>
                    <p>Back</p>
                </div>
                <div className={styles.title}>
                    <h2>REGISTRATION STEPS</h2>
                </div>
                <div className={styles.array}>
                    <ul className={styles.steps}>
                        <li className={styles.valid}>
                            <a href="../index.html" className={styles.retLi}>
                                <h2>1/ Search username</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li className={styles.valid}>
                            <a href="registration.html" className={styles.retLi}>
                                <h2>2/ Connect Wallet</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li className={styles.valid}>
                            <a href="registration.html" className={styles.retLi}>
                                <h2>3/ Claim Allocation</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li>
                            <h2>4/ Registration</h2>
                        </li>
                    </ul>
                </div>
            </div>
            <div className={styles.profile}>
                <div className={styles.status}>
                    <p>Available</p>
                </div>
                <img src="../img/berty_img.svg" alt="image of a parrot" />
                <p>brucelee.berty</p>
            </div>
            <div className={styles.learn}>
                <button className={`${styles.continueBtn} ${styles.button} ${styles.hov}`}>Learn More</button>
            </div>

        </div>

        <div className={styles.registrationForm}>
            <div className={styles.mint}>
                <img src="../img/coin.svg" />
                <p>The mint cost for this token is 100 $$$</p>
            </div>
            <ul>
                <li>
                    <p>Name (optional)</p>
                    <input type="text" placeholder="Type Name here" />
                </li>
                <li>
                    <p>Bio (optional)</p>
                    <input type="text" placeholder="Type Bio here" />
                </li>
                <li>
                    <p>Image URL (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
                <li>
                    <p>User Header Profile (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
                <li>
                    <p>Email (optional)</p>
                    <input type="text" placeholder="Type Email here" />
                </li>
                <li>
                    <p>Website (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>
                <li>
                    <p>Twitter (optional)</p>
                    <input type="text" placeholder="Link to Twitter" />
                </li>
                <li>
                    <p>Keybase.io (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>
                <li>
                    <p>Validator operator address (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>

                <li>
                    <p>User Header Profile (optional) (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
            </ul>
            <div className={styles.continue}>
                <button className={` ${styles.button} ${styles.openCard} ${styles.continueBtn}`}> Register your username</button>
            </div>
        </div>
    </section>


    <section className={styles.footer}>
      <div className={styles.colContainer}>
      <div className={styles.col1}>
        <img className={styles.logo} src="../img/berty_footer_logo.svg" alt="Berty' society logo"/>
        <p>The Berty app is developed by the NGO Berty Technologies.</p>
      </div>

      <div className={`${styles.col2} ${styles.strong}`}>
        <a href="#">Features</a>
        <a href="#">Challenges</a>
        <a href="#">FAQ</a>
        <a href="#">Community</a>
        <a href="#">Blog</a>
      </div>

      <div className={styles.col2}>
        <h4>Developpers</h4>
        <a href="#">Docs</a>
        <a href="#">Our Projects</a>
        <a href="#">Contribute</a>
        <a href="#">Projects we love</a>
      </div>

      <div className={styles.col2}>
        <h4>About Us</h4>
        <a href="#">Jobs</a>
        <a href="#">Newsletter</a>
        <a href="#">Contact</a>
        <a href="#">Press</a>
        <a href="#">Store</a>
        <a href="#">Assets</a>
      </div>
      </div>

      <div className={styles.copyright}>
      <div className={styles.copyrightTxt}>
        <p>Berty™️ is a registered trademark © 2018-2022 Berty Technologies - All right reserved - Terms & Conditions -
          Privacy Policy</p>
      </div>
      <div className={styles.follow}>
        <img className={styles.logo} src="../img/discord_logo.svg" alt="Discord logo"/>
        <img className={styles.logo} src="../img/twitter_logo.svg" alt="Tweeter logo"/>
        <img className={styles.logo} src="../img/github_logo.svg" alt="Github logo"/>
        <img className={styles.logo} src="../img/unknown_logo.svg" alt="Unknown logo"/>
        <img className={styles.logo} src="../img/linkedin_logo.svg" alt="Linkedin logo"/>
      </div>
    </div>
    </section>
      </div>
    </>
  )
}
