import Head from 'next/head'
import styles from '../styles/Registration.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Berty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Body}>
        <section className={styles.header}>
          <Link href="/">
            <img className={styles.logo} alt="Berty's company logo" src="../img/logo.svg" />
          </Link>
      <div>
        <ul className={styles.navbar}>
          <li><Link className={styles.hov} href="/vision">Vision</Link></li>
          <li><Link className={styles.hov} href="/roadmap">Roadmap</Link></li>
          <li><Link className={styles.hov} href="/">Contribute</Link></li>
          <a href="#" className={styles.close}><i className={`${styles.fa} ${styles.faTimes}`}></i></a>
        </ul>
    </div>
    <div  className={`${styles.barContainer} ${styles.mobile}`}>
      <i className={`${styles.faSolid} ${styles.faBars} ${styles.bar}`}></i>
    </div>
    </section>

    <section className={styles.registration}>

        <div className={styles.wrap}>
            <div className={styles.stepsArray}>
                <div className={styles.title}>
                    <h2>REGISTRATION STEPS</h2>
                </div>
                <div className={styles.array}>
                    <ul className={styles.steps}>
                        <li className={styles.valid}>
                            <a href="/" className={styles.retLi}>
                                <h2>1/ Search username</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li className={`${styles.current} ${styles.li1}`}>
                            <h2>2/ Connect Wallet</h2>
                            <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                        </li>
                        <li className={styles.li2}>
                            <h2>3/ Claim Allocation</h2>
                        </li>
                        <li>
                            <h2>4/ Registration</h2>
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        <div className={styles.connectArray}>
            <div className={styles.connect}>
                <h2>brucelee.berty</h2>
                <div className={styles.availableBtn}>Available</div>
            </div>
            <div className={styles.info}>
                <img src="../img/info_icon.svg" alt="information icon"/>
                <div className={styles.textContainer}>
                    <h2>What is a decentralized handle?</h2>
                    <p>Your account will be registred on a public distributed ledger, allowing to book it without
                        any
                        centralised authority. To register your account, you’ll need a wallet (Metamask or Keplr)
                        and
                        sign a transaction.</p>
                    <p><span className={styles.txtOrange}>4503 / 10 000</span> bertians have already booked their handle</p>
                </div>
            </div>
            <div className={`${styles.connect2} ${styles.reg1a}`}>
                <img src="../img/metamask_logo.svg" alt="Metamask icon"/>
                <div className={styles.lineContainer}>
                    <h2>Metamask</h2>
                    <button className={`${styles.connectBtn} ${styles.hov}`}>Connect</button>
                </div>
            </div>
            <div className={`${styles.connect2} ${styles.reg1b}`}>
                <img src="../img/kepler_logo.svg" alt="keplr icon"/>
                <div className={styles.lineContainer}>
                    <h2>Keplr Wallet</h2>
                    <button className={`${styles.connectBtn} ${styles.hov}`}>Connect</button>
                </div>
            </div>
            <div className={`${styles.connect2} ${styles.disabled} ${styles.reg2a}`}>
                <img src="../img/berty_mini_logo.svg" alt="minparrot icon"/>
                <div className={styles.lineContainer}>
                    <h2>Claim Berty Supporter Allocation (FreeMint)</h2>
                </div>
            </div>
            <div className={`${styles.connect2} ${styles.disabled} ${styles.reg2b}`}>
                <img src="../img/kepler_logo.svg" alt="coinbase icon"/>
                <div className={styles.lineContainer}>
                    <h2>Support the NGO by paying your handle</h2>
                </div>
            </div>
            <div className={`${styles.continue} ${styles.reg1c}`}>
                <button className={`${styles.continueBtn} ${styles.hov}`}>Continue</button>
            </div>
            <div className={`${styles.connect2} ${styles.disabled} ${styles.reg2c}`}>
                <button className={`${styles.continueBtn} ${styles.hov}`}>Learn More</button>
                <a className={`${styles.btnLink} ${styles.revhov}`} href="/registration2"><button className={styles.continueBtn}>Continue</button></a>
            </div>
        </div>
    </section>


    <section className={styles.footer}>
      <div className={styles.colContainer}>
      <div className={styles.col1}>
        <img className={styles.logo} src="../img/berty_footer_logo.svg" alt="Berty' society logo"/>
        <p>The Berty app is developed by the NGO Berty Technologies.</p>
      </div>

      <div className={`${styles.col2} ${styles.strong}`}>
        <a href="#">Features</a>
        <a href="#">Challenges</a>
        <a href="#">FAQ</a>
        <a href="#">Community</a>
        <a href="#">Blog</a>
      </div>

      <div className={styles.col2}>
        <h4>Developpers</h4>
        <a href="#">Docs</a>
        <a href="#">Our Projects</a>
        <a href="#">Contribute</a>
        <a href="#">Projects we love</a>
      </div>

      <div className={styles.col2}>
        <h4>About Us</h4>
        <a href="#">Jobs</a>
        <a href="#">Newsletter</a>
        <a href="#">Contact</a>
        <a href="#">Press</a>
        <a href="#">Store</a>
        <a href="#">Assets</a>
      </div>
      </div>

      <div className={styles.copyright}>
      <div className={styles.copyrightTxt}>
        <p>Berty™️ is a registered trademark © 2018-2022 Berty Technologies - All right reserved - Terms & Conditions -
          Privacy Policy</p>
      </div>
      <div className={styles.follow}>
        <img className={styles.logo} src="../img/discord_logo.svg" alt="Discord logo"/>
        <img className={styles.logo} src="../img/twitter_logo.svg" alt="Tweeter logo"/>
        <img className={styles.logo} src="../img/github_logo.svg" alt="Github logo"/>
        <img className={styles.logo} src="../img/unknown_logo.svg" alt="Unknown logo"/>
        <img className={styles.logo} src="../img/linkedin_logo.svg" alt="Linkedin logo"/>
      </div>
    </div>
    </section>
      </div>
    </>
  )
}
