import Head from 'next/head'
import styles from '../styles/Registration2.module.css'
import Header from '../components/header/header'
import Footer from '../components/footer/footer'


export default function Registration2() {
  return (
    <>
      <Head>
        <title>Berty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Body}>

    <Header />

    <section className={styles.registration3}>
        <div className={styles.leftWrapper}>
            <div className={styles.stepsArray}>
                <div className={styles.back}>
                    <a href="/registration"><img src="../img/arrow.png" alt="Back arrow icon"/>
                    </a>
                    <p>Back</p>
                </div>
                <div className={styles.title}>
                    <h2>REGISTRATION STEPS</h2>
                </div>
                <div className={styles.array}>
                    <ul className={styles.steps}>
                        <li className={styles.valid}>
                            <a href="/" className={styles.retLi}>
                                <h2>1/ Search username</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li className={styles.valid}>
                            <a href="/registration" className={styles.retLi}>
                                <h2>2/ Connect Wallet</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li className={styles.valid}>
                            <a href="/registration" className={styles.retLi}>
                                <h2>3/ Claim Allocation</h2>
                                <img src="../img/valid_icon.svg" alt="Green completion icon"/>
                            </a>
                        </li>
                        <li>
                            <h2>4/ Registration</h2>
                        </li>
                    </ul>
                </div>
            </div>
            <div className={styles.profile}>
                <div className={styles.status}>
                    <p>Available</p>
                </div>
                <img src="../img/berty_img.svg" alt="image of a parrot" />
                <p>brucelee.berty</p>
            </div>
            <div className={styles.learn}>
                <button className={`${styles.continueBtn} ${styles.button} ${styles.hov}`}>Learn More</button>
            </div>

        </div>

        <div className={styles.registrationForm}>
            <div className={styles.mint}>
                <img src="../img/coin.svg" />
                <p>The mint cost for this token is 100 $$$</p>
            </div>
            <ul>
                <li>
                    <p>Name (optional)</p>
                    <input type="text" placeholder="Type Name here" />
                </li>
                <li>
                    <p>Bio (optional)</p>
                    <input type="text" placeholder="Type Bio here" />
                </li>
                <li>
                    <p>Image URL (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
                <li>
                    <p>User Header Profile (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
                <li>
                    <p>Email (optional)</p>
                    <input type="text" placeholder="Type Email here" />
                </li>
                <li>
                    <p>Website (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>
                <li>
                    <p>Twitter (optional)</p>
                    <input type="text" placeholder="Link to Twitter" />
                </li>
                <li>
                    <p>Keybase.io (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>
                <li>
                    <p>Validator operator address (optional)</p>
                    <input type="text" placeholder="Type/insert link here" />
                </li>

                <li>
                    <p>User Header Profile (optional) (optional)</p>
                    <input type="text" placeholder="Insert image URL here" />
                </li>
            </ul>
            <div className={styles.continue}>
                <button className={` ${styles.button} ${styles.openCard} ${styles.continueBtn}`}> Register your username</button>
            </div>
        </div>
    </section>

    <Footer/>

      </div>
    </>
  )
}
