import Head from 'next/head';
import styles from '../styles/Vision.module.css';
import Header from '../components/header/header';
import Footer from '../components/footer/footer';

export default function Vision() {
  return (
    <>
      <Head>
        <title>Berty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.Body}>
        <Header />

        <section className={styles.content}>
          <div className={styles.contentContainer}>
            <div className={styles.title}>
              <h1>
                VISI
                <img
                  src="../img/visiontitle.svg"
                  alt="planet image  symbolizing the o letter in vision"
                />
                N
              </h1>
            </div>

            <div className={`${styles.simpleContainer} ${styles.mb93}`}>
              <div className={`${styles.subtitleContainer} ${styles.disabled}`}>
                <h2>PLOP</h2>
              </div>
              <div className={styles.subcontentContainer}>
                <div className={styles.textContainer}>
                  <p>
                    We live in an era of accelerated change. The pace of innovation is unprecedented
                    and the emergence of new technologies like Web 3 tools unlocks a ton of
                    opportunities. Today, thanks to these amazing technologies, anyone can create a
                    sustainable business without making any compromises. Let’s write it down: The
                    era of concessions is now over. Let’s do the right thing, for the right
                    purposes. Let's redefine together what is achievable and what we really hope for
                    in the future. Everyone has the individual power to decide - and it starts with
                    a simple yet fundamental thing such as choosing a communication solution.
                  </p>
                </div>
                <div className={`${styles.imgContainer} ${styles.mb20}`}>
                  <img src="../img/vision1.svg" alt="telescope image" />
                </div>
              </div>
            </div>

            <div className={`${styles.simpleContainer} ${styles.mb93}`}>
              <div className={`${styles.subtitleContainer} ${styles.mb60}`}>
                <h2>Berty, a communication tool</h2>
              </div>
              <div className={`${styles.subcontentContainer} ${styles.rowrev}`}>
                <div className={styles.textContainer}>
                  <p>
                    Over the past decade, instant messaging applications have become increasingly
                    popular. WhatsApp, Facebook Messenger, Telegram and WeChat are certainly among
                    the best-known. Have you ever wondered, will these applications still exist in
                    10, 20 or even 30 years? Do you foresee these applications still existing in
                    2050? <br />
                    To us, none of today’s messenger solutions are able to bring certain degree of
                    confidence to use it, without fearing censorship or surveillance and were able
                    to ensure that our own data would not be used against us, we decided to build
                    our own. Berty is a new kind of messenger. It is decentralized, unstoppable,
                    <br />
                    un-censurable, secure, made for the future, and in a pure open source spirit.
                  </p>
                </div>
                <div className={`${styles.imgContainer} ${styles.mr53}`}>
                  <img src="../img/vision2.svg" alt="artificial satellite image" />
                </div>
              </div>
            </div>

            <div className={`${styles.simpleContainer} ${styles.mb27}`}>
              <div className={`${styles.subtitleContainer} ${styles.mb20}`}>
                <h2 className={styles.txtalignend}>Berty embraces the Web3 revolution</h2>
              </div>
              <div className={styles.subcontentContainer}>
                <div className={styles.textContainer}>
                  <p>
                    Centralization has allowed billions of people to access the World Wide Web and
                    create the stable and robust infrastructure on which it is based. At the same
                    time, a handful of centralized entities have taken control of large parts of the
                    World Wide Web, unilaterally deciding what is and is not allowed.Web3 is the
                    answer to this dilemma. Unlike a Web dominated by large technology companies,
                    Web3 is decentralized and is built, operated and owned by its users. Web3 gives
                    power to individuals rather than corporations.
                    <br />
                    <br />
                    Web3 is about digital sovereignty for individuals, businesses and governments.
                    It means no longer letting anyone decide for everyone what the Internet should
                    look like.
                  </p>
                </div>
                <div className={styles.imgContainer}>
                  <img src="../img/vision3.svg" alt="asteroid image" />
                </div>
              </div>
            </div>

            <div className={`${styles.tripleContainer} ${styles.mb60}`}>
              <div className={styles.miniContainer}>
                <div className={`${styles.titleCont} ${styles.mb55}`}>
                  <h2>Berty is decentralized</h2>
                </div>
                <div className={`${styles.imgCont} ${styles.mb37}`}>
                  <img src="../img/vision4a.svg" alt="image of a network" />
                </div>
                <div className={styles.txtCont}>
                  <p>
                    Instead of large parts of the Internet being owned and controlled by a few
                    centralized entities, ownership in Berty is distributed among its creators and
                    users.
                  </p>
                </div>
              </div>

              <div className={styles.miniContainer}>
                <div className={`${styles.titleCont} ${styles.mb55}`}>
                  <h2>Berty is open</h2>
                </div>
                <div className={`${styles.imgCont} ${styles.mb37}`}>
                  <img src="../img/vision4b.svg" alt="image of an antenna " />
                </div>
                <div className={styles.txtCont}>
                  <p>
                    Everyone has equal access to contribute to Berty, and no one can be excluded.
                    Berty was built for the community and by the community.
                  </p>
                </div>
              </div>

              <div className={styles.miniContainer}>
                <div className={`${styles.titleCont} ${styles.mb55}`}>
                  <h2>Berty is trustless</h2>
                </div>
                <div className={`${styles.imgCont} ${styles.mb37}`}>
                  <img src="../img/vision4c.svg" alt="image of a shield" />
                </div>
                <div className={styles.txtCont}>
                  <p>
                    Berty does not rely on trusted third parties and stands on a very basic concept:
                    no one trusts anyone.
                  </p>
                </div>
              </div>
            </div>

            <div className={`${styles.simpleContainer} ${styles.mb32}`}>
              <div className={`${styles.subtitleContainer} ${styles.mb32}`}>
                <h2>Privacy should be a basic standard, not a fancy option</h2>
              </div>
              <div className={`${styles.subcontentContainer} ${styles.rowrev}`}>
                <div className={styles.textContainer}>
                  <p>
                    The right to privacy is a fundamental right. It protects people from being
                    targeted or tracked by others and guarantees personal space. Privacy should no
                    longer be fashionable, nor a cool feature to have. It should be a standard.
                    <br />
                    <br /> That's one of the reasons why Berty is designed to be privacy responsible
                    and why even as a founding team we have no access to your data. Furthermore, we
                    have made the choice to be an NGO and not a for-profit entity. Privacy is not a
                    business model.
                  </p>
                </div>
                <div className={`${styles.imgContainer} ${styles.ml17}`}>
                  <img src="../img/vision5.svg" alt="fingerprint image" />
                </div>
              </div>
            </div>

            <div className={styles.simpleContainer}>
              <div className={`${styles.subtitleContainer} ${styles.mb32}`}>
                <h2 className={styles.txtalignend}>
                  Unstoppable communication! Berty is future-ready
                </h2>
              </div>
              <div className={styles.subcontentContainer}>
                <div className={styles.textContainer}>
                  <p>
                    Unfortunately, we think tomorrow will be made of obstacles. So to go further in
                    the thinking process, Berty is designed to be a messenger that enables
                    communication that can withstand the obstacles that may come our way. They can
                    be natural, like an earthquake, a tornado (think Haiti) or man-made: the madness
                    of censorship and surveillance of certain individuals out of the sheer urge to
                    control populations (think China). Or maybe even tomorrow we will be in areas
                    never explored before (think of Mars). We don't know what the future is. We just
                    want to be prepared and make Berty the communication tool that can withstand
                    whatever obstacles may come our way. In short, Berty, your next unstoppable
                    messenger, no matter what.
                    <br />
                    <br />
                    We are committed to creating the best future-proof communication app ever made.
                    Join us in this amazing and necessary journey.
                  </p>
                </div>
                <div className={`${styles.imgContainer} ${styles.mr29} ${styles.mb60}`}>
                  <img src="../img/vision6.svg" alt="rised fist image" />
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
